/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Funciones.BasededatosManager;
import Funciones.RendererTabla;
import java.awt.Color;
import java.sql.ResultSet;

/**
 *
 * @author Misael
 */
public class Ventas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ventas
     */
    int idempleado=0;
    BasededatosManager bd=new BasededatosManager();
    public Ventas(int idempleado) {
        initComponents();
        this.idempleado=idempleado;
        ResultSet consulta=bd.consultar("SELECT P.idpedidos,CONCAT(E.nombres,' ',E.apellidos)as Empleado, C.nombre, P.cantidad, P.total, P.iva, P.totalneto FROM pedidos P, Empleados E, clientes C WHERE P.Empleados_idEmpleados=E.idempleados AND C.idclientes=P.clientes_idclientes AND P.Empleados_idEmpleados='"+idempleado+"';");
        String[]nomcolumnas=new String[]{"ID","Nombre Empleado","Nombre Cliente","Cantidad Pizzas","Total","IVA","Total Neto"};
        jTable1.setModel(bd.llenarTabla(7, nomcolumnas, consulta));
        jTable1.getColumnModel().getColumn(0).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(1).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(2).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(3).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(4).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(5).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(6).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(0).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
        jTable1.getColumnModel().getColumn(5).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
        jTable1.getColumnModel().getColumn(6).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Chulo's Pizza: Gerente - Registros de Ventas");

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pedido", "Empleado", "Cliente", "Cantidad", "Total", "IVA", "Total Neto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setBackground(new java.awt.Color(255, 204, 0));
        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton4.setText("ACTUALIZAR TABLA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ResultSet consulta=bd.consultar("SELECT P.idpedidos,CONCAT(E.nombres,' ',E.apellidos)as Empleado, C.nombre, P.cantidad, P.total, P.iva, P.totalneto FROM pedidos P, Empleados E, clientes C WHERE P.Empleados_idEmpleados=E.idempleados AND C.idclientes=P.clientes_idclientes AND P.Empleados_idEmpleados='"+idempleado+"';");
        String[]nomcolumnas=new String[]{"ID","Nombre Empleado","Nombre Cliente","Cantidad Pizzas","Total","IVA","Total Neto"};
        jTable1.setModel(bd.llenarTabla(7, nomcolumnas, consulta));
        jTable1.getColumnModel().getColumn(0).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(1).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(2).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(3).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(4).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(5).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(6).setHeaderRenderer(new RendererTabla(new Color(255,204,0),new Color(204,0,0)));
        jTable1.getColumnModel().getColumn(0).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
        jTable1.getColumnModel().getColumn(5).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
        jTable1.getColumnModel().getColumn(6).setCellRenderer(new RendererTabla(new Color(204,0,0), new Color(255,204,0)));
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
